name: 'imgword'
costFn: 'crossEntIdx'
decisionFn: 'argmax'
stages:
    - 'imgSel'
    - 'imgFeat'
    - 'imgFeatNorm'
    - 'softmax'
outputs: 'softmax'
specs:
    - name: 'imgSel'
      type: 'selector'
      inputs: 'input'
      start: 0
      end: 1
      axis: 1
    - name: 'imgFeat'
      type: 'lut'
      inputs: 'imgSel'
      inputDim: 123288
      outputDim: 4096
      initWeights: '/ais/gobi3/u/mren/data/cocoqa-full/hidden_oxford.h5'
      sparse: true
      format: 'h5'
      h5key: 'hidden7'
      learningRate: 0.0
    - name: 'imgFeatNorm'
      type: 'normalize'
      inputs: 'imgFeat'
      mean: '/ais/gobi3/u/mren/data/cocoqa-full/hidden_oxford.h5'
      meanKey: 'hidden7_mean'
      std: '/ais/gobi3/u/mren/data/cocoqa-full/hidden_oxford.h5'
      stdKey: 'hidden7_std'
      format: 'h5'
      outputDim: 4096
    - name: 'softmax'
      type: 'map'
      inputs: 'imgFeatNorm'
      activeFn: 'softmax'
      outputDim: 412
      initRange: 0.1
      initSeed: 7
      learningRate: 0.01
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 15.0
      weightRegConst: 0.00005
      outputdEdX: false