costFn: 'crossEntIdx'
decisionFn: 'argmax'
stages:
    - 'imgSel'
    - 'imgFeat'
    - 'txtSel'
    - 'sentVec'
    - 'softmax'
outputs: 'softmax'
specs:
    - name: 'imgSel'
      type: 'selector'
      inputs: 'input'
      start: 0
      end: 1
      axis: 1
    - name: 'txtSel'
      type: 'selector'
      inputs: 'input'
      start: 1
      end: 2
      axis: 1
    - name: 'imgFeat'
      type: 'lut'
      inputs: 'imgSel'
      inputDim: 1449
      outputDim: 4096
      initWeights: '/ais/gobi3/u/mren/data/nyu-depth/hidden_oxford.h5'
      format: 'h5'
      h5key: 'hidden7'
      learningRate: 0.0
      outputdEdX: false
    - name: 'sentVec'
      type: 'lut'
      inputs: 'txtSel'
      intConversion: true
      inputDim: 7109
      outputDim: 300
      initWeights: '/ais/gobi3/u/mren/data/daquar-37/skip_sent_vec.npy'
      learningRate: 0.0
      outputdEdX: false
    - name: 'softmax'
      type: 'map'
      inputs: 'sentVec, imgFeat'
      activeFn: 'softmax'
      outputDim: 67
      initRange: 0.001
      initSeed: 7
      learningRate: 0.01
      momentum: 0.9
      gradientClip: 0.01
      weightClip: 15.0
      weightRegConst: 0.00005