costFn: 'crossEntIdx'
decisionFn: 'argmax'
stages:
    - 'imgSel'
    - 'txtSel'
    - 'txtDict'
    - 'txtFold'
    - 'imgFeat'
    - 'imgFeatNorm'
    - 'imgMapFirst'
    - 'imgMapLast'
    - 'imgFoldFirst'
    - 'imgFoldLast'
    - 'concat'
    - 'concatRev'
    - 'concatLast'
    - 'concatLastRev'
    - 'dropout'
    - 'lstm'
    - 'answer'
outputs: 'answer'
specs:
    - name: 'imgSel'
      type: 'selector'
      inputs: 'input'
      start: 0
      end: 1
      axis: 1
    - name: 'txtSel'
      type: 'selector'
      inputs: 'input'
      start: 1
      end: 56
      axis: 1
    - name: 'txtDict'
      type: 'lut'
      inputs: 'txtSel'
      intConversion: true
      inputDim: 9738
      outputDim: 500
      initRange: 1.0
      initSeed: 2
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 1000.0
      outputdEdX: false
    - name: 'txtFold'
      type: 'timeFold'
      inputs: 'txtDict'
      timespan: 55
    - name: 'imgFeat'
      type: 'lut'
      inputs: 'imgSel'
      inputDim: 123288
      outputDim: 4096
      initWeights: '/ais/gobi3/u/mren/data/cocoqa-full/hidden_oxford.h5'
      sparse: true
      format: 'h5'
      h5key: 'hidden7'
      learningRate: 0.0
      outputdEdX: false
    - name: 'imgFeatNorm'
      type: 'normalize'
      inputs: 'imgFeat'
      mean: '/ais/gobi3/u/mren/data/cocoqa-full/hidden_oxford.h5'
      meanKey: 'hidden7_mean'
      std: '/ais/gobi3/u/mren/data/cocoqa-full/hidden_oxford.h5'
      stdKey: 'hidden7_std'
      format: 'h5'
      outputDim: 4096
    - name: 'imgMapFirst'
      type: 'map'
      inputs: 'imgFeatNorm'
      activeFn: 'identity'
      outputDim: 500
      bias: false
      initRange: 0.05
      initSeed: 1
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      outputdEdX: false
    - name: 'imgMapLast'
      type: 'map'
      inputs: 'imgFeatNorm'
      activeFn: 'identity'
      outputDim: 500
      bias: false
      initRange: 0.05
      initSeed: 15
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      outputdEdX: false
    - name: 'imgFoldFirst'
      type: 'timeFold'
      inputs: 'imgMapFirst'
      timespan: 1
    - name: 'imgFoldLast'
      type: 'timeFold'
      inputs: 'imgMapLast'
      timespan: 1
    - name: 'concat'
      type: 'concat'
      inputs: 'imgFoldFirst, txtFold'
      axis: 1
    - name: 'concatRev'
      type: 'timeReverse'
      inputs: 'concat'
    - name: 'concatLast'
      type: 'concat'
      inputs: 'imgFoldLast, concatRev'
      axis: 1
    - name: 'concatLastRev'
      type: 'timeReverse'
      inputs: 'concatLast'
    - name: 'dropout'
      type: 'dropout'
      inputs: 'concatLastRev'
      dropoutRate: 0.2
      initSeed: 3
      outputDim: 500
    - name: 'lstm'
      type: 'lstm'
      inputs: 'dropout'
      inputDim: 500
      outputDim: 300
      timespan: 56
      initRange: 0.05
      initSeed: 4
      cutOffZeroEnd: true
      multiOutput: false
      learningRate: 0.8
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      weightRegConst: 0.00005
    - name: 'answer'
      type: 'map'
      inputs: 'lstm'
      outputDim: 431
      activeFn: 'softmax'
      initRange: 0.1
      initSeed: 6
      learningRate: 0.01
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 15.0
      weightRegConst: 0.00005