name: 'imgword'
costFn: 'crossEntIdx'
decisionFn: 'argmax'
stages:
    - 'imgSel'
    - 'imgUnfold'
    - 'imgFeat'
    - 'txtSel'
    - 'txtUnfold'
    - 'txtDict'
    - 'txtFold'
    - 'dropout'
    - 'lstm'
    - 'softmax'
outputs: 'softmax'
specs:
    - name: 'imgSel'
      type: 'selector'
      inputs: 'input'
      start: 0
      end: 1
      axis: 1
    - name: 'txtSel'
      type: 'selector'
      inputs: 'input'
      start: 1
      end: 56
      axis: 1
    - name: 'imgUnfold'
      type: 'timeUnfold'
      inputs: 'imgSel'
    - name: 'imgFeat'
      type: 'lut'
      inputs: 'imgUnfold'
      inputDim: 123288
      outputDim: 4096
      initWeights: '/ais/gobi3/u/mren/data/cocoqa-full/hidden_oxford.h5'
      sparse: true
      format: 'h5'
      h5key: 'hidden7'
      learningRate: 0.0
      outputdEdX: false
    - name: 'txtUnfold'
      type: 'timeUnfold'
      inputs: 'txtSel'
    - name: 'txtDict'
      type: 'lut'
      intConversion: true
      inputs: 'txtUnfold'
      inputDim: 9738
      outputDim: 500
      initRange: 1.0
      initSeed: 2
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 1000.0
      outputdEdX: false
    - name: 'txtFold'
      type: 'timeFold'
      inputs: 'txtDict'
      timespan: 55
    - name: 'dropout'
      type: 'dropout'
      inputs: 'txtFold'
      dropoutRate: 0.2
      initSeed: 3
      outputDim: 300
    - name: 'lstm'
      type: 'lstm'
      inputs: 'dropout'
      inputDim: 500
      outputDim: 300
      timespan: 55
      initRange: 0.1
      initSeed: 4
      cutOffZeroEnd: true
      multiErr: false
      learningRate: 0.8
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      weightRegConst: 0.00005
    - name: 'softmax'
      type: 'map'
      inputs: 'lstm, imgFeat'
      activeFn: 'softmax'
      outputDim: 431
      initRange: 0.1
      initSeed: 7
      learningRate: 0.01
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 50.0
      weightRegConst: 0.00005