costFn: 'crossEntIdx'
decisionFn: 'argmax'
stages:
    - 'imgSel'
    - 'imgFeat'
    - 'txtSel'
    - 'sentVec'
    - 'softmax'
outputs: 'softmax'
specs:
    - name: 'imgSel'
      type: 'selector'
      inputs: 'input'
      start: 0
      end: 1
      axis: 1
    - name: 'txtSel'
      type: 'selector'
      inputs: 'input'
      start: 1
      end: 2
      axis: 1
    - name: 'imgFeat'
      type: 'lut'
      inputs: 'imgSel'
      inputDim: 1449
      outputDim: 4096
      initWeights: '/ais/gobi3/u/mren/data/cocoqa-full/hidden_oxford.h5'
      format: 'h5'
      h5key: 'hidden7'
      sparse: true
      learningRate: 0.0
      outputdEdX: false
    - name: 'sentVec'
      type: 'lut'
      inputs: 'txtSel'
      intConversion: true
      inputDim: 117684
      outputDim: 3400
      initWeights: '/ais/gobi3/u/mren/data/cocoqa-full/skip_sent_vec.npy'
      learningRate: 0.0
      outputdEdX: false
    - name: 'softmax'
      type: 'map'
      inputs: 'sentVec, imgFeat'
      activeFn: 'softmax'
      outputDim: 431
      initRange: 0.001
      initSeed: 7
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      weightRegConst: 0.00005