costFn: 'crossEntIdx'
decisionFn: 'argmax'
stages:
    - 'imgSel'
    - 'imgUnfold'
    - 'imgFeat'
    - 'imgFeatNorm'
    - 'txtSel'
    - 'txtUnfold'
    - 'txtDict'
    - 'txtFold'
    - 'bow'
    - 'mapping'
    - 'answer'
outputs: 'answer'
specs:
    - name: 'imgSel'
      type: 'selector'
      inputs: 'input'
      start: 0
      end: 1
      axis: 1
    - name: 'txtSel'
      type: 'selector'
      inputs: 'input'
      start: 1
      end: 56
      axis: 1
    - name: 'imgUnfold'
      type: 'timeUnfold'
      inputs: 'imgSel'
    - name: 'imgFeat'
      type: 'lut'
      inputs: 'imgUnfold'
      inputDim: 123288
      outputDim: 4096
      initWeights: '/ais/gobi3/u/mren/data/cocoqa-full/hidden_oxford.h5'
      sparse: true
      format: 'h5'
      h5key: 'hidden7'
      learningRate: 0.0
      outputdEdX: false
    - name: 'imgFeatNorm'
      type: 'normalize'
      inputs: 'imgFeat'
      mean: '/ais/gobi3/u/mren/data/cocoqa-full/hidden_oxford.h5'
      meanKey: 'hidden7_mean'
      std: '/ais/gobi3/u/mren/data/cocoqa-full/hidden_oxford.h5'
      stdKey: 'hidden7_std'
      format: 'h5'
      outputDim: 4096
    - name: 'txtUnfold'
      type: 'timeUnfold'
      inputs: 'txtSel'
    - name: 'txtDict'
      type: 'lut'
      intConversion: true
      inputs: 'txtUnfold'
      inputDim: 3399
      outputDim: 500
      initRange: 1.0
      initSeed: 2
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 1000.0
      outputdEdX: false
    - name: 'txtFold'
      type: 'timeFold'
      inputs: 'txtDict'
      timespan: 55
    - name: 'bow'
      type: 'sum2'
      inputs: 'txtFold'
      outputDim: 500
    - name: 'mapping'
      type: 'map'
      inputs: 'bow, imgFeatNorm'
      activeFn: 'identity'
      outputDim: 1
      initRange: 0.001
      initSeed: 5
      learningRate: 0.01
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 10.0
      weightRegConst: 0.00005
    - name: 'answer'
      type: 'ordinal'
      inputs: 'mapping'
      fixExtreme: true
      outputDim: 11
      learningRate: 0.01
      momentum: 0.9
      gradientClip: 0.01
      weightClip: 15.0
      weightRegConst: 0.00005
