costFn: 'crossEntIdx'
decisionFn: 'argmax'
stages:
    - 'imgSel1'
    - 'imgFeat'
    - 'imgFold'
    - 'txtSel1'
    - 'txtDict'
    - 'txtFold'
    - 'attModel'
outputs: 'attModel'
specs:
    - name: 'imgSel1'
      type: 'selector'
      inputs: 'input'
      start: 0
      end: 1
      axis: 1
    - name: 'txtSel1'
      type: 'selector'
      inputs: 'input'
      start: 1
      end: 6
      axis: 1
    - name: 'imgFeat'
      type: 'lut'
      inputs: 'imgSel1'
      inputDim: 123287
      outputDim: 100352
      initWeights: '/ais/gobi3/u/mren/data/cocoqa-full/hidden_oxford.h5'
      format: 'h5'
      h5key: 'hidden5_4_conv'
      sparse: true
      learningRate: 0.0
      outputdEdX: false
    - name: 'txtDict'
      type: 'lut'
      inputs: 'txtSel1'
      inputDim: 90
      outputDim: 300
      initRange: 1.0
      initSeed: 2
      learningRate: 0.0
      outputdEdX: false
    - name: 'imgFold'
      type: 'timeFold'
      inputs: 'imgFeat'
      timespan: 1
    - name: 'txtFold'
      type: 'timeFold'
      inputs: 'txtDict'
      timespan: 5
    - name: 'imgSel2'
      type: 'selector'
      inputs: 'input($0)'
      start: 0
      end: 100352
      recurrent: true
    - name: 'txtSel2'
      type: 'selector'
      inputs: 'input'
      start: 1
      end: 100652
      recurrent: true
    - name: 'imgReshape'
      type: 'reshape'
      inputs: 'imgSel2($0)'
      reshapeFn: '(x[0], 196, x[1]/196)'
      outputDim: 512
      recurrent: true
    - name: 'attReshape'
      type: 'reshape'
      inputs: 'attOut(-1)'
      reshapeFn: '(x[0], x[1], 1)'
      outputDim: 196
      recurrent: true
    - name: 'attCtx'
      type: 'sumProd'
      inputs: 'attReshape, imgReshape($0)'
      sumAxis: 1
      outputDim: 512
      recurrent: true
    - name: 'ilstm'
      type: 'lstm'
      inputs: 'attCtx, txtSel2'
      inputDim: 812
      outputDim: 150
      timespan: 27
      initRange: 0.1
      initSeed: 4
      cutOffZeroEnd: true
      multiErr: true
      learningRate: 0.8
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      weightRegConst: 0.00005
      outputdEdX: true
    - name: 'attHid1'
      type: 'map'
      inputs: 'txtSel2, ilstm'
      outputDim: 196
      activeFn: 'tanh'
      initRange: 0.1
      initSeed: 6
      learningRate: 0.1
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 50
      recurrent: true
    - name: 'attOut'
      type: 'map'
      inputs: 'attHid1'
      outputDim: 196
      activeFn: 'softmax'
      defaultValue: 0.00510204081632653
      initRange: 0.1
      initSeed: 7
      learningRate: 0.1
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 50
      recurrent: true
    - name: 'attModel'
      type: 'recurrent'
      inputs: 'imgFold, txtFold'
      stages:
          - 'imgSel2'
          - 'txtSel2'
          - 'imgReshape'
          - 'attReshape'
          - 'attCtx'
          - 'ilstm'
          - 'attHid1'
          - 'attOut'
      outputs: 'attOut'
      inputDim: 100652
      outputDim: 196
      timespan: 6
      multiOutput: false