name: 'bow'
costFn: 'crossEntIdx'
decisionFn: 'argmax'
stages:
    - 'imgSel'
    - 'imgUnfold'
    - 'imgFeat'
    - 'imgFeatNorm'
    - 'imgMap'
    - 'txtSel'
    - 'txtUnfold'
    - 'txtDict'
    - 'txtFold'
    - 'bow'
    - 'dropout'
    - 'hidden'
    - 'softmax'
outputs: 'softmax'
specs:
    - name: 'imgSel'
      type: 'selector'
      inputs: 'input'
      start: 0
      end: 1
      axis: 1
    - name: 'txtSel'
      type: 'selector'
      inputs: 'input'
      start: 1
      end: 28
      axis: 1
    - name: 'imgUnfold'
      type: 'timeUnfold'
      inputs: 'imgSel'
      outputdEdX: false
    - name: 'imgFeat'
      type: 'lut'
      inputs: 'imgSel'
      inputDim: 1449
      outputDim: 4096
      initWeights: '/ais/gobi3/u/mren/data/nyu-depth/hidden_oxford.h5'
      format: 'h5'
      h5key: 'hidden7'
      learningRate: 0.0
    - name: 'imgFeatNorm'
      type: 'normalize'
      inputs: 'imgFeat'
      mean: '/ais/gobi3/u/mren/models/coco_vgg/mean.npy'
      std: '/ais/gobi3/u/mren/models/coco_vgg/std.npy'
      outputDim: 4096
    - name: 'imgMap'
      type: 'map'
      inputs: 'imgFeatNorm'
      activeFn: 'identity'
      bias: false
      outputDim: 300
      initRange: 0.1
      initSeed: 1
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
    - name: 'imgFold'
      type: 'timeFold'
      inputs: 'imgMap'
      timespan: 1
    - name: 'txtUnfold'
      type: 'timeUnfold'
      inputs: 'txtSel'
      outputdEdX: false
    - name: 'txtDict'
      type: 'lut'
      inputs: 'txtUnfold'
      inputDim: 868
      outputDim: 300
      initRange: 0.1
      initSeed: 2
      learningRate: 0.0
    - name: 'txtFold'
      type: 'timeFold'
      inputs: 'txtDict'
      timespan: 27
    - name: 'bow'
      type: 'sum2'
      inputs: 'txtFold'
      numComponents: 27
      outputDim: 300
    - name: 'dropout'
      inputs: 'bow, imgMap'
      type: 'dropout'
      dropoutRate: 0.5
      initSeed: 3
      outputDim: 600
    - name: 'hidden'
      inputs: 'dropout'
      type: 'map'
      activeFn: 'tanh'
      initRange: 0.1
      initSeed: 2
      outputDim: 600
      learningRate: 0.1
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      weightRegConst: 0.00005
    - name: 'softmax'
      type: 'map'
      inputs: 'hidden'
      activeFn: 'softmax'
      outputDim: 68
      initRange: 0.1
      initSeed: 7
      learningRate: 0.01
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 15.0
      weightRegConst: 0.00005
